Category.find_or_create_by(name: 'Gemischter Chor')
Category.find_or_create_by(name: 'Frauenchor')
Category.find_or_create_by(name: 'Männerchor')
Category.find_or_create_by(name: 'Kinderchor')
Category.find_or_create_by(name: 'Jugendchor')
Category.find_or_create_by(name: 'Seniorenchor')
